added required methods and some changes for python 3 compatability
ALBA-Synchrotron/sardana-adlink pull request #2
Opened 2020-08-27 11:23 UTC by 13bscsaamjad

- `class_prop` are not working well with sardana3; changed to `ctrl_properties` which is better for having different properties for different equipment.
- added required `PreStartAll` and `StartOne` methods for sardana 3.
- remove CT suffix from methods which does not seems to work with sardana 3.

2020-08-28 16:29 UTC, reszelaz requested changes
Many thanks Abdullah for the changes! Thanks to this PR I discovered that I wrongly made the `StartOne()` mandatory. Could you check my comments and make the necessary changes?

2020-08-28 16:29 UTC, reszelaz commented on sardana_adlink/ctrl/AdlinkAICoTiCtrl.py
> +    def PreStartAll(self):
I think this is not mandatory to re-implement it.

2020-08-28 16:29 UTC, reszelaz commented on sardana_adlink/ctrl/AdlinkAICoTiCtrl.py
> +    def StartOne(self, axis, value=None):
Sorry this is bug in Sardana that I introduced. It whould not be mandatory to implement it - see https://github.com/sardana-org/sardana/pull/1403.

2020-08-31 08:23 UTC, 13bscsaamjad commented
Thanks for the review. I have now removed `StartOne` and `PreStartAll`.

2020-09-01 14:37 UTC, rhomspuron requested changes
Could you remove this change? We will do it on the integration.

2020-09-01 15:28 UTC, 13bscsaamjad commented
@rhomspuron sorry, which one?

2020-09-01 15:29 UTC, 13bscsaamjad reviewed
reviewed

2020-09-02 06:52 UTC, rhomspuron commented
Hi @13bscsaamjad, 

Sorry I did not select the correct file. Could you revert the bump version commit? We use the bumpversion: https://pypi.org/project/bumpversion/, to change the version. It changes two files at the same time: setup.py and .bumpversion.cfg, and creates a tag for the version. We recommend to not change by hand the version, we will do it  after to integrate the PR.

Thanks,
Roberto

2020-09-08 07:28 UTC, merged